<?php
return [
    'BE' => [
        'debug' => true,
        'enabledBeUserIPLock' => '1',
        'installToolPassword' => '$P$ClG7p0XC1ajAtOaT41N1C0UAtIlWL7/',
        'loginSecurityLevel' => 'normal',
        'versionNumberInFilename' => '0',
    ],
    'DB' => [
        'Connections' => [
            'Default' => [
                'charset' => 'utf8',
                'dbname' => '[Set via env]',
                'driver' => 'mysqli',
                'host' => '[Set via env]',
                'password' => '[Set via env]',
                'user' => '[Set via env]',
            ],
        ],
        'extTablesDefinitionScript' => 'extTables.php',
    ],
    'EXT' => [
        'extConf' => [
            'addheaderwizard' => 'a:0:{}',
            'aeurltool' => 'a:0:{}',
            'bootstrap_grids' => 'a:1:{s:19:"enableGridSimpleRow";s:1:"0";}',
            'builder' => 'a:0:{}',
            'compatibility6' => 'a:1:{s:15:"setPageTSconfig";s:1:"1";}',
            'cs_seo' => 'a:12:{s:17:"enablePathSegment";s:1:"0";s:15:"realURLAutoConf";s:1:"0";s:11:"tsConfigPid";s:1:"1";s:8:"maxTitle";s:3:"100";s:14:"maxDescription";s:3:"250";s:11:"maxNavTitle";s:3:"150";s:12:"inPageModule";s:1:"0";s:18:"evaluationDoktypes";s:1:"1";s:10:"evaluators";s:38:"Title,Description,H1,H2,Images,Keyword";s:8:"minTitle";s:2:"40";s:14:"minDescription";s:3:"100";s:5:"maxH2";s:1:"6";}',
            'fal_ttnews' => 'a:2:{s:13:"media_add_ref";s:1:"1";s:20:"media_add_orig_field";s:1:"0";}',
            'fancybox' => 'a:0:{}',
            'feedit' => 'a:0:{}',
            'fluid_styled_content' => 'a:0:{}',
            'fluidpages' => 'a:3:{s:8:"autoload";s:1:"1";s:8:"doktypes";s:0:"";s:33:"pagesLanguageConfigurationOverlay";s:1:"0";}',
            'graphic_header' => 'a:0:{}',
            'indexed_search' => 'a:17:{s:8:"pdftools";s:9:"/usr/bin/";s:8:"pdf_mode";s:2:"20";s:5:"unzip";s:9:"/usr/bin/";s:6:"catdoc";s:9:"/usr/bin/";s:6:"xlhtml";s:9:"/usr/bin/";s:7:"ppthtml";s:9:"/usr/bin/";s:5:"unrtf";s:9:"/usr/bin/";s:9:"debugMode";s:1:"0";s:18:"fullTextDataLength";s:1:"0";s:23:"disableFrontendIndexing";s:1:"0";s:6:"minAge";s:2:"24";s:6:"maxAge";s:1:"0";s:16:"maxExternalFiles";s:1:"5";s:26:"useCrawlerForExternalFiles";s:1:"0";s:11:"flagBitMask";s:3:"192";s:16:"ignoreExtensions";s:0:"";s:17:"indexExternalURLs";s:1:"0";}',
            'jh_magnificpopup' => 'a:2:{s:19:"colPosOfIrreContent";s:3:"109";s:19:"enableAlphaFeatures";s:1:"0";}',
            'lfeditor' => 'a:4:{s:13:"viewLanguages";s:0:"";s:15:"defaultLanguage";s:0:"";s:9:"extIgnore";s:23:"/^(CVS|.svn|.git|csh_)/";s:13:"changeXlfDate";s:1:"1";}',
            'linkvalidator' => 'a:0:{}',
            'my_redirects' => 'a:0:{}',
            'news' => 'a:14:{s:13:"prependAtCopy";s:1:"1";s:6:"tagPid";s:1:"1";s:12:"rteForTeaser";s:1:"0";s:22:"contentElementRelation";s:1:"0";s:13:"manualSorting";s:1:"0";s:19:"categoryRestriction";s:4:"none";s:34:"categoryBeGroupTceFormsRestriction";s:1:"0";s:19:"dateTimeNotRequired";s:1:"0";s:11:"archiveDate";s:4:"date";s:24:"showAdministrationModule";s:1:"1";s:35:"hidePageTreeForAdministrationModule";s:1:"0";s:12:"showImporter";s:1:"1";s:18:"storageUidImporter";s:1:"1";s:22:"resourceFolderImporter";s:12:"/news_import";}',
            'news_fal_migration' => 'a:0:{}',
            'news_falttnewsimport' => 'a:0:{}',
            'news_ttnewsimport' => 'a:0:{}',
            'newscalendar' => 'a:0:{}',
            'nwt_imagecrop' => 'a:0:{}',
            'object_path' => 'a:0:{}',
            'perfectlightbox' => 'a:0:{}',
            'phpmyadmin' => 'a:4:{s:12:"hideOtherDBs";s:1:"1";s:9:"uploadDir";s:21:"uploads/tx_phpmyadmin";s:10:"allowedIps";s:0:"";s:12:"useDevIpMask";s:1:"0";}',
            'powermail' => 'a:17:{s:12:"disableIpLog";s:1:"0";s:27:"disableMarketingInformation";s:1:"0";s:20:"disableBackendModule";s:1:"0";s:24:"disablePluginInformation";s:1:"0";s:35:"disablePluginInformationMailPreview";s:1:"0";s:13:"enableCaching";s:1:"0";s:15:"l10n_mode_merge";s:1:"0";s:29:"replaceIrreWithElementBrowser";s:1:"0";s:28:"enableTableGarbageCollection";s:1:"0";s:7:"useIRRE";s:1:"1";s:10:"usePreview";s:1:"0";s:11:"TabDividers";s:1:"1";s:14:"feusersPrefill";s:70:"name, address, telephone, fax, email, zip, city, country, www, company";s:12:"disableIPlog";s:1:"0";s:22:"disablePMRealUrlConfig";s:1:"0";s:16:"disableStartStop";s:1:"1";s:12:"cssSelection";s:1:"0";}',
            'realurl' => 'a:7:{s:10:"configFile";s:26:"typo3conf/realurl_conf.php";s:14:"enableAutoConf";s:1:"0";s:14:"autoConfFormat";s:1:"0";s:17:"segTitleFieldList";s:0:"";s:12:"enableDevLog";s:1:"0";s:10:"moduleIcon";s:1:"0";s:19:"enableChashUrlDebug";s:1:"0";}',
            'rgsmoothgallery' => 'a:2:{s:11:"splitRecord";s:2:"\\n";s:12:"splitComment";s:1:"|";}',
            'rmd_htmlextractor' => 'a:0:{}',
            'rte_ckeditor' => 'a:1:{s:15:"ckeditorVersion";s:1:"1";}',
            'rtehtmlarea' => 'a:19:{s:21:"noSpellCheckLanguages";s:23:"ja,km,ko,lo,th,zh,b5,gb";s:15:"AspellDirectory";s:15:"/usr/bin/aspell";s:20:"defaultConfiguration";s:95:"Demo (Show-off configuration. Includes pre-configured styles. Not for production environments.)";s:12:"enableImages";s:1:"1";s:20:"enableInlineElements";s:1:"0";s:19:"allowStyleAttribute";s:1:"1";s:24:"enableAccessibilityIcons";s:1:"0";s:16:"forceCommandMode";s:1:"0";s:17:"defaultDictionary";s:2:"en";s:14:"dictionaryList";s:2:"en";s:16:"enableDAMBrowser";s:1:"0";s:18:"enableClickEnlarge";s:1:"0";s:22:"enableMozillaExtension";s:1:"0";s:14:"enableInOpera9";s:1:"1";s:15:"enableDebugMode";s:1:"0";s:23:"enableCompressedScripts";s:1:"1";s:20:"mozAllowClipboardURL";s:0:"";s:18:"plainImageMaxWidth";s:1:"0";s:19:"plainImageMaxHeight";s:1:"0";}',
            'rtgnewscalendar' => 'a:0:{}',
            'saltedpasswords' => 'a:2:{s:3:"BE.";a:4:{s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\PhpassSalt";s:11:"forceSalted";i:0;s:15:"onlyAuthService";i:0;s:12:"updatePasswd";i:1;}s:3:"FE.";a:5:{s:7:"enabled";i:0;s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\PhpassSalt";s:11:"forceSalted";i:0;s:15:"onlyAuthService";i:0;s:12:"updatePasswd";i:1;}}',
            'shortcut_redirect' => 'a:0:{}',
            'sourceopt' => 'a:0:{}',
            'static_info_tables' => 'a:3:{s:13:"enableManager";s:1:"0";s:7:"charset";s:5:"utf-8";s:12:"usePatch1822";s:1:"0";}',
            't3devcarousel' => 'a:0:{}',
            't3devslickcarousel' => 'a:0:{}',
            't3jquery' => 'a:14:{s:15:"alwaysIntegrate";s:1:"1";s:17:"integrateToFooter";s:1:"0";s:17:"enableStyleStatic";s:1:"0";s:18:"dontIntegrateOnUID";s:0:"";s:23:"dontIntegrateInRootline";s:0:"";s:13:"jqLibFilename";s:23:"jquery-###VERSION###.js";s:9:"configDir";s:19:"uploads/tx_t3jquery";s:13:"jQueryVersion";s:6:"1.11.x";s:15:"jQueryUiVersion";s:0:"";s:18:"jQueryTOOLSVersion";s:0:"";s:22:"jQueryBootstrapVersion";s:0:"";s:16:"integrateFromCDN";s:1:"1";s:11:"locationCDN";s:6:"google";s:13:"updateMessage";s:1:"0";}',
            't3quixplorer' => 'a:10:{s:9:"no_access";s:5:"^\\.ht";s:11:"show_hidden";s:1:"1";s:8:"home_url";s:0:"";s:8:"home_dir";s:0:"";s:11:"show_thumbs";s:1:"1";s:15:"textarea_height";s:2:"30";s:14:"auto_highlight";s:1:"1";s:12:"disable_text";s:1:"1";s:12:"editable_ext";s:215:"\\.phpcron$|\\.ts$|\\.tmpl$|\\.txt$|\\.php$|\\.php3$|\\.phtml$|\\.inc$|\\.sql$|\\.pl$|\\.htm$|\\.html$|\\.shtml$|\\.dhtml$|\\.xml$|\\.js$|\\.css$|\\.cgi$|\\.cpp$\\.c$|\\.cc$|\\.cxx$|\\.hpp$|\\.h$|\\.pas$|\\.p$|\\.java$|\\.py$|\\.sh$\\.tcl$|\\.tk$";s:8:"php_path";s:3:"php";}',
            'templavoila' => 'a:3:{s:7:"enable.";a:3:{s:13:"oldPageModule";s:1:"0";s:19:"selectDataStructure";s:1:"0";s:15:"renderFCEHeader";s:1:"0";}s:9:"staticDS.";a:3:{s:6:"enable";s:1:"0";s:8:"path_fce";s:27:"fileadmin/templates/ds/fce/";s:9:"path_page";s:28:"fileadmin/templates/ds/page/";}s:13:"updateMessage";s:1:"0";}',
            'timtilch_lightbox' => 'a:0:{}',
            'tmpl' => 'a:2:{s:14:"enableOnColPos";s:1:"0";s:21:"enableOnGridColumnIds";s:3:"111";}',
            'tmpl_migration' => 'a:1:{s:12:"enableDevLog";s:1:"1";}',
            'tt_news' => 'a:23:{s:17:"requireCategories";s:1:"0";s:18:"useInternalCaching";s:1:"1";s:11:"cachingMode";s:6:"normal";s:13:"cacheLifetime";s:1:"0";s:13:"cachingEngine";s:8:"internal";s:17:"showBackEndModule";s:1:"0";s:13:"prependAtCopy";s:1:"1";s:5:"label";s:5:"title";s:9:"label_alt";s:0:"";s:10:"label_alt2";s:0:"";s:15:"label_alt_force";s:1:"0";s:25:"l10n_mode_prefixLangTitle";s:1:"1";s:22:"l10n_mode_imageExclude";s:1:"1";s:20:"hideNewLocalizations";s:1:"0";s:24:"writeCachingInfoToDevlog";s:1:"0";s:23:"writeParseTimesToDevlog";s:1:"0";s:18:"parsetimeThreshold";s:3:"0.1";s:13:"useStoragePid";s:1:"0";s:11:"treeOrderBy";s:3:"uid";s:21:"categorySelectedWidth";s:1:"0";s:17:"categoryTreeWidth";s:1:"0";s:13:"noTabDividers";s:1:"0";s:18:"categoryTreeHeigth";s:1:"5";}',
            'typoscript_code' => 'a:0:{}',
            'vhs' => 'a:0:{}',
            'vostokzapad_site' => 'a:0:{}',
            'vostokzapadesign_site' => 'a:0:{}',
            'ws_last_modified' => 'a:0:{}',
            'ws_scss' => 'a:0:{}',
        ],
    ],
    'EXTCONF' => [
        'lang' => [
            'availableLanguages' => [],
        ],
    ],
    'FE' => [
        'debug' => true,
        'disableNoCacheParameter' => '0',
        'pageNotFound_handling' => '/page-not-found/',
    ],
    'GFX' => [
        'gdlib_png' => '1',
        'processor' => 'GraphicsMagick',
        'processor_allowTemporaryMasksAsPng' => false,
        'processor_colorspace' => 'RGB',
        'processor_effects' => -1,
        'processor_enabled' => true,
        'processor_path' => '/usr/bin/',
        'processor_path_lzw' => '/usr/bin/',
    ],
    'INSTALL' => [],
    'MAIL' => [
        'defaultMailFromAddress' => 'noreply@vostokzapadesign.ru',
        'defaultMailFromName' => '',
        'transport' => 'smtp',
        'transport_sendmail_command' => '/usr/sbin/sendmail -t -i ',
        'transport_smtp_encrypt' => 'ssl',
        'transport_smtp_password' => 'G3Kph8YF',
        'transport_smtp_server' => 'smtp.timeweb.ru:465',
        'transport_smtp_username' => 'noreply@vostokzapadesign.ru',
    ],
    'SYS' => [
        'devIPmask' => '*',
        'displayErrors' => 1,
        'enableDeprecationLog' => 'file',
        'encryptionKey' => '86b294f3f91e65403f9775300c494f4a',
        'exceptionalErrors' => 28674,
        'sitename' => 'Восток-Запад',
        'sqlDebug' => 1,
        'systemLogLevel' => 0,
        'trustedHostsPattern' => '.*',
    ],
];
