<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tmpl"
 *
 * Auto generated by Extension Builder 2018-09-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Site Template',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Dmitry Vasilev, Pavlov Sergey',
    'author_email' => 'dmitry@t3dev.ru, pavlovsg@yandex.ru',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
