<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "t3devcarousel"
 *
 * Auto generated by Extension Builder 2016-06-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Slick Carousel',
	'description' => 'Slick Carousel',
	'category' => 'plugin',
	'author' => 'Dmitry Vasiliev',
	'author_email' => 'dmitry@typo3.ru.net',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
            'typo3' => '9.5.0-9.5.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);